{"uid":"fa7d57ae9fea2d07","name":"test_token","fullName":"test_case.test_1#test_token","historyId":"50ae9a4b8473c930ed5afd964acfb2bd","time":{"start":1753963463165,"stop":1753963463165,"duration":0},"status":"passed","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":3,"retriesStatusChange":true,"beforeStages":[{"name":"_session_faker","time":{"start":1753963462062,"stop":1753963462257,"duration":195},"status":"passed","steps":[],"attachments":[],"parameters":[],"hasContent":false,"stepsCount":0,"attachmentStep":false,"shouldDisplayMessage":false,"attachmentsCount":0},{"name":"sc_login","time":{"start":1753963462258,"stop":1753963463164,"duration":906},"status":"passed","steps":[],"attachments":[],"parameters":[],"hasContent":false,"stepsCount":0,"attachmentStep":false,"shouldDisplayMessage":false,"attachmentsCount":0},{"name":"event_loop_policy","time":{"start":1753963462258,"stop":1753963462258,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"hasContent":false,"stepsCount":0,"attachmentStep":false,"shouldDisplayMessage":false,"attachmentsCount":0}],"afterStages":[],"labels":[{"name":"parentSuite","value":"test_case"},{"name":"suite","value":"test_1"},{"name":"host","value":"5CD2323XZM"},{"name":"thread","value":"19100-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"test_case.test_1"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[{"uid":"b1fad0482c167655","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPSConnectionPool(host='192.192.100.100', port=443): Max retries exceeded with url: /api/v1.2/randString (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000028EFC834590>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))","time":{"start":1753963414827,"stop":1753963414827,"duration":0}},{"uid":"ad81ab32fbba6a69","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPSConnectionPool(host='192.192.100.100', port=443): Max retries exceeded with url: /api/v1.2/randString (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000018DC1344D90>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))","time":{"start":1753957651476,"stop":1753957651476,"duration":0}},{"uid":"9d411aeba59268f3","status":"passed","time":{"start":1753946650192,"stop":1753946650193,"duration":1}}],"categories":[],"tags":[]},"source":"fa7d57ae9fea2d07.json","parameterValues":[]}